import requests
import polars as pl
import sys
from typing import List
import time
import sqlite3

territory_list = {
    'Q31354462': 'Republic of Abkhazia',
    'Q889': 'Islamic Emirate of Afghanistan',
    'Q37362': 'Sovereign Base Areas of Akrotiri and Dhekelia',
    'Q5689': 'Åland',
    'Q222': 'Republic of Albania',
    'Q262': 'People\'s Democratic Republic of Algeria',
    'Q16641': 'American Samoa',
    'Q228': 'Principality of Andorra',
    'Q916': 'Republic of Angola',
    'Q25228': 'Anguilla',
    'Q781': 'Antigua and Barbuda',
    'Q414': 'Argentine Republic',
    'Q399': 'Republic of Armenia',
    'Q21203': 'Country of Aruba',
    'Q46197': 'Ascension Island',
    'Q408': 'Commonwealth of Australia',
    'Q40': 'Republic of Austria',
    'Q227': 'Republic of Azerbaijan',
    'Q778': 'Commonwealth of the Bahamas',
    'Q398': 'Kingdom of Bahrain',
    'Q902': 'People\'s Republic of Bangladesh',
    'Q244': 'Barbados',
    'Q184': 'Republic of Belarus',
    'Q31': 'Kingdom of Belgium',
    'Q242': 'Belize',
    'Q962': 'Republic of Benin',
    'Q23635': 'Bermuda',
    'Q917': 'Kingdom of Bhutan',
    'Q750': 'Plurinational State of Bolivia',
    'Q25396': 'Bonaire',
    'Q225': 'Bosnia and Herzegovina',
    'Q963': 'Republic of Botswana',
    'Q155': 'Federative Republic of Brazil',
    'Q25305': 'Virgin Islands',
    'Q921': 'Brunei Darussalam',
    'Q219': 'Republic of Bulgaria',
    'Q965': 'Burkina Faso',
    'Q967': 'Republic of Burundi',
    'Q424': 'Kingdom of Cambodia',
    'Q1009': 'Republic of Cameroon',
    'Q16': 'Canada',
    'Q1011': 'Republic of Cabo Verde',
    'Q5785': 'Cayman Islands',
    'Q929': 'Central African Republic',
    'Q657': 'Republic of Chad',
    'Q298': 'Republic of Chile',
    'Q148': 'People\'s Republic of China',
    'Q31063': 'Territory of Christmas Island',
    'Q36004': 'Territory of Cocos (Keeling) Islands',
    'Q739': 'Republic of Colombia',
    'Q970': 'Union of the Comoros',
    'Q971': 'Republic of the Congo',
    'Q26988': 'Cook Islands',
    'Q800': 'Republic of Costa Rica',
    'Q224': 'Republic of Croatia',
    'Q241': 'Republic of Cuba',
    'Q25279': 'Country of Curaçao',
    'Q229': 'Republic of Cyprus',
    'Q213': 'Czech Republic',
    'Q35': 'Kingdom of Denmark',
    'Q977': 'Republic of Djibouti',
    'Q784': 'Commonwealth of Dominica',
    'Q786': 'Dominican Republic',
    'Q974': 'Democratic Republic of the Congo',
    'Q574': 'Democratic Republic of Timor-Leste',
    'Q14452': 'Easter Island',
    'Q736': 'Republic of Ecuador',
    'Q79': 'Arab Republic of Egypt',
    'Q792': 'Republic of El Salvador',
    'Q21': 'England',
    'Q983': 'Republic of Equatorial Guinea',
    'Q986': 'State of Eritrea',
    'Q191': 'Republic of Estonia',
    'Q1050': 'Kingdom of Eswatini',
    'Q115': 'Federal Democratic Republic of Ethiopia',
    'Q9648': 'Falkland Islands',
    'Q4628': 'Faroe Islands',
    'Q702': 'Federated States of Micronesia',
    'Q712': 'Republic of Fiji',
    'Q33': 'Republic of Finland',
    'Q142': 'French Republic',
    'Q3769': 'French Guiana',
    'Q30971': 'French Polynesia',
    'Q1000': 'Gabonese Republic',
    'Q1005': 'Republic of the Gambia',
    'Q230': 'Georgia',
    'Q183': 'Federal Republic of Germany',
    'Q117': 'Republic of Ghana',
    'Q1410': 'Gibraltar',
    'Q170488': 'Gozo',
    'Q41': 'Hellenic Republic',
    'Q223': 'Greenland',
    'Q769': 'Grenada',
    'Q17012': 'Guadeloupe',
    'Q16635': 'Guam',
    'Q774': 'Republic of Guatemala',
    'Q3311985': 'Guernsey',
    'Q1006': 'Republic of Guinea',
    'Q1007': 'Republic of Guinea-Bissau',
    'Q734': 'Co-operative Republic of Guyana',
    'Q790': 'Republic of Haiti',
    'Q782': 'Hawaii',
    'Q783': 'Republic of Honduras',
    'Q8646': 'Hong Kong',
    'Q28': 'Hungary',
    'Q189': 'Iceland',
    'Q668': 'Republic of India',
    'Q252': 'Republic of Indonesia',
    'Q794': 'Islamic Republic of Iran',
    'Q796': 'Republic of Iraq',
    'Q27': 'Republic of Ireland',
    'Q9676': 'Isle of Man',
    'Q9679': 'Isle of Wight',
    'Q180209': 'Isles of Scilly',
    'Q801': 'State of Israel',
    'Q38': 'Italian Republic',
    'Q1008': 'Republic of Côte d\'Ivoire',
    'Q766': 'Jamaica',
    'Q17': 'Japan',
    'Q785': 'Bailiwick of Jersey',
    'Q810': 'Hashemite Kingdom of Jordan',
    'Q232': 'Republic of Kazakhstan',
    'Q114': 'Republic of Kenya',
    'Q710': 'Republic of Kiribati',
    'Q1246': 'Republic of Kosovo',
    'Q817': 'State of Kuwait',
    'Q813': 'Kyrgyz Republic',
    'Q819': 'Lao People\'s Democratic Republic',
    'Q211': 'Republic of Latvia',
    'Q822': 'Republic of Lebanon',
    'Q1013': 'Kingdom of Lesotho',
    'Q1014': 'Republic of Liberia',
    'Q1016': 'State of Libya',
    'Q347': 'Principality of Liechtenstein',
    'Q37': 'Republic of Lithuania',
    'Q32': 'Grand Duchy of Luxembourg',
    'Q14773': 'Macau',
    'Q1019': 'Republic of Madagascar',
    'Q26253': 'Autonomous Region of Madeira',
    'Q1020': 'Republic of Malawi',
    'Q833': 'Malaysia',
    'Q826': 'Republic of Maldives',
    'Q912': 'Republic of Mali',
    'Q233': 'Republic of Malta',
    'Q709': 'Republic of the Marshall Islands',
    'Q17054': 'Martinique',
    'Q1025': 'Islamic Republic of Mauritania',
    'Q1027': 'Republic of Mauritius',
    'Q17063': 'Department of Mayotte',
    'Q96': 'United Mexican States',
    'Q217': 'Republic of Moldova',
    'Q235': 'Principality of Monaco',
    'Q711': 'Mongolia',
    'Q236': 'Montenegro',
    'Q13353': 'Montserrat',
    'Q1028': 'Kingdom of Morocco',
    'Q1029': 'Republic of Mozambique',
    'Q836': 'Republic of the Union of Myanmar',
    'Q1030': 'Republic of Namibia',
    'Q697': 'Republic of Nauru',
    'Q837': 'Federal Democratic Republic of Nepal',
    'Q55': 'Kingdom of the Netherlands',
    'Q33788': 'New Caledonia',
    'Q664': 'New Zealand',
    'Q811': 'Republic of Nicaragua',
    'Q1032': 'Republic of the Niger',
    'Q1033': 'Federal Republic of Nigeria',
    'Q34020': 'Niue',
    'Q31057': 'Norfolk Island',
    'Q423': 'Democratic People\'s Republic of Korea',
    'Q221': 'Republic of North Macedonia',
    'Q23681': 'Turkish Republic of Northern Cyprus',
    'Q26': 'Northern Ireland',
    'Q16644': 'Commonwealth of the Northern Mariana Islands',
    'Q20': 'Kingdom of Norway',
    'Q842': 'Sultanate of Oman',
    'Q100166': 'Orkney',
    'Q843': 'Islamic Republic of Pakistan',
    'Q695': 'Republic of Palau',
    'Q219060': 'State of Palestine',
    'Q804': 'Republic of Panama',
    'Q691': 'Independent State of Papua New Guinea',
    'Q733': 'Republic of Paraguay',
    'Q419': 'Republic of Peru',
    'Q928': 'Republic of the Philippines',
    'Q35672': 'Pitcairn, Henderson, Ducie and Oeno Islands',
    'Q36': 'Republic of Poland',
    'Q45': 'Portuguese Republic',
    'Q1183': 'Commonwealth of Puerto Rico',
    'Q846': 'State of Qatar',
    'Q17070': 'Réunion',
    'Q218': 'Romania',
    'Q159': 'Russian Federation',
    'Q1037': 'Republic of Rwanda',
    'Q25528': 'Saba',
    'Q40362': 'Sahrawi Arab Democratic Republic',
    'Q34497': 'Saint Helena',
    'Q763': 'Federation of Saint Kitts and Nevis',
    'Q760': 'Saint Lucia',
    'Q126125': 'Saint Martin',
    'Q34617': 'Territorial Collectivity of Saint Pierre and Miquelon',
    'Q757': 'Saint Vincent and the Grenadines',
    'Q25362': 'Collectivité territoriale de Saint-Barthélemy',
    'Q683': 'Independent State of Samoa',
    'Q238': 'Republic of San Marino',
    'Q1039': 'Democratic Republic of São Tomé and Príncipe',
    'Q851': 'Kingdom of Saudi Arabia',
    'Q22': 'Scotland',
    'Q1041': 'Republic of Senegal',
    'Q403': 'Republic of Serbia',
    'Q1042': 'Republic of Seychelles',
    'Q1044': 'Republic of Sierra Leone',
    'Q334': 'Republic of Singapore',
    'Q26180': 'Sint Eustatius',
    'Q26273': 'Sint Maarten',
    'Q214': 'Slovak Republic',
    'Q215': 'Republic of Slovenia',
    'Q685': 'Solomon Islands',
    'Q1045': 'Federal Republic of Somalia',
    'Q34754': 'Republic of Somaliland',
    'Q258': 'Republic of South Africa',
    'Q884': 'Republic of Korea',
    'Q23427': 'Republic of South Ossetia',
    'Q958': 'Republic of South Sudan',
    'Q190353': 'Sovereign Military Hospitaller Order of Saint John of Jerusalem, of Rhodes and of Malta',
    'Q29': 'Kingdom of Spain',
    'Q854': 'Democratic Socialist Republic of Sri Lanka',
    'Q1049': 'Republic of the Sudan',
    'Q730': 'Republic of Suriname',
    'Q34': 'Kingdom of Sweden',
    'Q39': 'Swiss Confederation',
    'Q858': 'Syrian Arab Republic',
    'Q865': 'Republic of China',
    'Q863': 'Republic of Tajikistan',
    'Q924': 'United Republic of Tanzania',
    'Q869': 'Kingdom of Thailand',
    'Q945': 'Togolese Republic',
    'Q36823': 'Tokelau',
    'Q678': 'Kingdom of Tonga',
    'Q907112': 'Pridnestrovian Moldavian Republic',
    'Q754': 'Republic of Trinidad and Tobago',
    'Q220982': 'Tristan da Cunha',
    'Q948': 'Republic of Tunisia',
    'Q43': 'Republic of Türkiye',
    'Q874': 'Turkmenistan',
    'Q18221': 'Turks and Caicos Islands',
    'Q672': 'Tuvalu',
    'Q11703': 'Virgin Islands of the United States',
    'Q1036': 'Republic of Uganda',
    'Q212': 'Ukraine',
    'Q878': 'United Arab Emirates',
    'Q30': 'United States of America',
    'Q77': 'Oriental Republic of Uruguay',
    'Q265': 'Republic of Uzbekistan',
    'Q686': 'Republic of Vanuatu',
    'Q237': 'Vatican City State',
    'Q717': 'Bolivarian Republic of Venezuela',
    'Q881': 'Socialist Republic of Vietnam',
    'Q25': 'Wales',
    'Q35555': 'Territory of the Wallis and Futuna Islands',
    'Q805': 'Republic of Yemen',
    'Q953': 'Republic of Zambia',
    'Q1774': 'Zanzibar',
    'Q954': 'Republic of Zimbabwe',
}


def func():
    pass